worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;

    server {
        listen 8080;
        server_name _;

        root /var/www/html/public;
        index index.php index.html;

        client_max_body_size 20M;

        location = / {
            try_files /index.html =404;
}

        location = /app/ {
            try_files /app/index.html =404;
}

        location / {
            try_files $uri $uri/ /index.php$is_args$args;
}

        location ~ ^/index\.php(/|$) {
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_split_path_info ^(.+\.php)(/.*)$;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
            fastcgi_param DOCUMENT_ROOT $realpath_root;
            internal;
        }

        location ~ \.php$ {
            return 404;
        }
    }
}